function [D_A_out_r, D_A_out_i, D_B_out_r, D_B_out_i, ...
    D_11, D_12, D_21, D_22, ...
    D_A_r, D_A_i, D_B_r, D_B_i] = ...
    COMPLEX_PE_out_D(...
    X_in_A, Y_in_A, X_in_B, Y_in_B, ...
    Iteration, CORDIC_mode, direction,...
    D_11, D_12, D_21, D_22, ...
    D_A_r, D_A_i, D_B_r, D_B_i, ...
    ...
    WL_H, FL_H, WL_P_input, FL_P_input, trunc_mode,...
    fid_PI, fid_S, fid_THETA_E, ...
    fid_out_stage1_r, fid_out_stage1_i, fid_out_stage1_p, ...
    WL_S, FL_S, WL_PI, FL_PI)

%[X_11, Y_11, D_11_reg] = CORDIC_unit(X_in_A, Y_in_A, D_11, Iteration, CORDIC_mode);
%[X_21, Y_21, D_21_reg] = CORDIC_unit(X_in_B, Y_in_B, D_21, Iteration, CORDIC_mode);
%[X_out_A, Y_out_A, D_12_reg] = CORDIC_unit(X_11, X_21, D_12, Iteration, CORDIC_mode);

[mag_simple, mag_strict, X_11, Y_11, D_11_reg] = ...
    CORDIC_unit_trunc(X_in_A, Y_in_A, D_11, Iteration, CORDIC_mode, ...
    WL_H, FL_H, WL_P_input, FL_P_input, trunc_mode,...
    fid_PI, fid_S, fid_THETA_E, "false",...
    fid_out_stage1_r, fid_out_stage1_i, fid_out_stage1_p, ...
    WL_S, FL_S, WL_PI, FL_PI);
[mag_simple, mag_strict, X_21, Y_21, D_21_reg] = ...
    CORDIC_unit_trunc(X_in_B, Y_in_B, D_21, Iteration, CORDIC_mode, ...
    WL_H, FL_H, WL_P_input, FL_P_input, trunc_mode,...
    fid_PI, fid_S, fid_THETA_E, "false",...
    fid_out_stage1_r, fid_out_stage1_i, fid_out_stage1_p, ...
    WL_S, FL_S, WL_PI, FL_PI);
[mag_simple, mag_strict, X_out_A, Y_out_A, D_12_reg] = ...
    CORDIC_unit_trunc(X_11, X_21, D_12, Iteration, CORDIC_mode, ...
    WL_H, FL_H, WL_P_input, FL_P_input, trunc_mode,...
    fid_PI, fid_S, fid_THETA_E, "false",...
    fid_out_stage1_r, fid_out_stage1_i, fid_out_stage1_p, ...
    WL_S, FL_S, WL_PI, FL_PI);
%[X_out_B, Y_out_B, D_22_reg] = CORDIC_unit(Y_11, Y_21, D_22, Iteration, CORDIC_mode);


% 已經是output了:
if CORDIC_mode == "Vector"
    D_11 = -D_11_reg;
    D_21 = -D_21_reg;
    D_12 = -D_12_reg;
    %D_22 = -D_22_reg;
[D_A_r, D_A_out_r] = shift_reg(D_A_r, X_out_A, direction);
[D_A_i, D_A_out_i] = shift_reg(D_A_i, Y_out_A, direction);
[D_B_r, D_B_out_r] = shift_reg(D_B_r, 0, direction);
[D_B_i, D_B_out_i] = shift_reg(D_B_i, 0, direction);
elseif CORDIC_mode == "Rotation"
    %[X_out_B, Y_out_B, D_22_reg] = CORDIC_unit(Y_11, Y_21, D_12, Iteration, CORDIC_mode);
    [mag_simple, mag_strict, X_out_B, Y_out_B, D_22_reg] = ...
    CORDIC_unit_trunc(Y_11, Y_21, D_12, Iteration, CORDIC_mode, ...
    WL_H, FL_H, WL_P_input, FL_P_input, trunc_mode,...
    fid_PI, fid_S, fid_THETA_E, "false",...
    fid_out_stage1_r, fid_out_stage1_i, fid_out_stage1_p, ...
    WL_S, FL_S, WL_PI, FL_PI);
    D_11 = D_11_reg;
    D_21 = D_21_reg;
    D_12 = D_12_reg;
    D_22 = D_22_reg;
[D_A_r, D_A_out_r] = shift_reg(D_A_r, X_out_A, direction);
[D_A_i, D_A_out_i] = shift_reg(D_A_i, X_out_B, direction);
[D_B_r, D_B_out_r] = shift_reg(D_B_r, Y_out_A, direction);
[D_B_i, D_B_out_i] = shift_reg(D_B_i, Y_out_B, direction);
end

%D_A_r, D_A_out_r] = shift_reg(D_A_r, X_out_A, direction);
%D_A_i, D_A_out_i] = shift_reg(D_A_i, X_out_B, direction);
%D_B_r, D_B_out_r] = shift_reg(D_B_r, Y_out_A, direction);
%D_B_i, D_B_out_i] = shift_reg(D_B_i, Y_out_B, direction);
end